### ISSUE TITLE
Multiboot not working for Hoenn games

### ISSUE THREAD

**Issue by sbower213** [Lorenzooone/Pokemon-Gen3-to-Gen-X#1]
Hi there! I downloaded version 1.0.1 onto my Analogue Pocket to multiboot onto my GBA. I was able to get the multiboot to recognize my copy of LeafGreen, however my copies of Ruby, Sapphire, and Emerald would only display "Error reading the data!" after multiboot completed. Do you have any insight on how to get the Hoenn games to read properly?

**Comment by Lorenzooone** [comment]
Hi! I've been already reported this issue. I was investigating whether it was a problem with REG_WAITCNT, but that doesn't seem to be it.
Do you have any way of dumping your games' save data? I'd like to understand what is going wrong, because I actually developed this while using both E and RS, and I had no issues...
Thanks!

**Comment by sbower213** [comment]
sure, here's a link to my emerald save file: https://we.tl/t-21CDUhlIZO

**Comment by Lorenzooone** [comment]
Hmm... Weird, I can read it just fine. There are a couple of issues, but they don't prevent the homebrew from working for me.

May I ask you to try running the new "Currently Read Info" debug option I added to the main menu and to report to me the results with your Emerald cartridge inserted? It will take about a minute. It's in the attached zip.
Thanks!

[pokemon_gen3_to_genx_mb_debug.zip](https://github.com/Lorenzooone/Pokemon-Gen3-to-Gen-X/files/11032472/pokemon_gen3_to_genx_mb_debug.zip)

**Comment by sbower213** [comment]
```
Game: E
0x1F1C08FB
0xDC382911
0x1362
0x1362
```

**Comment by sbower213** [comment]
Interestingly, I booted this with my copy of Sapphire again and it actually worked. I may have misremembered trying both ruby and sapphire earlier, or perhaps the game wasn't all the way in or something? I can get you a backup of my sapphire file if you need, this is the output when run with that game:
```
Game: S
0x554DEDC4
0xDC382911
0x8012025
0x8012025
```

As an aside, I tried to select "swap cartridge" and switch in my ruby game but it quit out of the program entirely and started to boot ruby as normal. Is there a trick to getting that feature to work?

**Comment by Lorenzooone** [comment]
> 0x1362
> 0x1362

So... The ROM is reading fine.
The issue seems to be that it's not reading SRAM correctly.
So it may be something as simple as the carts not being fully inserted...

How are you multibooting? Are you multibooting without the cart inserted? Or do you have the cart in, then press Start + Select on the GBA logo, and then multiboot? I'd suggest the latter method, if you aren't doing it already...?

The Swap Cartridge and Load Cartridge options execute the same exact loading routine as the one executed when multibooting. So it seems to be an issue like that...

**Comment by Lorenzooone** [comment]
Actually, if you still have issues with Emerald, could you try running this version of the debug build?

I think it maaaay have something to do with the banks. But I need proof.
[pokemon_gen3_to_genx_mb_debug2.zip](https://github.com/Lorenzooone/Pokemon-Gen3-to-Gen-X/files/11032859/pokemon_gen3_to_genx_mb_debug2.zip)

**Comment by sbower213** [comment]
I'm doing the latter start + select method with the cart already inserted to get into multiboot. Here's the latest output from Emerald:

```
Game: E
0x1F1C08FB
0x8C162460
0x1362
0x1362
0x1362
```

**Comment by Lorenzooone** [comment]
Found the issue! It's still in ID mode, and reporting the Flash ID, which is Sanyo, or 0x1362. ( https://problemkaputt.de/gbatek.htm#gbacartbackupflashrom )
I have all carts with Macronix flash, so I did not know this, but it NEEDS a second Term command that I am missing.
I am doing some other checks to make sure it fully works.

**Comment by sbower213** [comment]
Ahh, interesting, I didn't know there were multiple kinds of chips used for these games. Thanks for looking into this!

**Comment by Lorenzooone** [comment]
Can you please try v1.0.2 that I just released?
It should be it. I can't test it myself though, so I really need your feedback. Also, if it loads, try making a trade or changing the clock, and report to me whether it crashed during saving, or it worked fine.
Thanks!

**Comment by sbower213** [comment]
Looks good to me! I got both my Emerald and Ruby games to successfully trade with my copy of Crystal. The only quirk with the trade as far as I can tell is that the Original Trainer of my Crystal pokemon shows up as male in Emerald, while it's actually a female in Crystal. Changing the time also worked fine. Thanks for fixing this issue!

**Comment by Lorenzooone** [comment]
Did you trade those Pokémon to Gen 1 before? Because I am testing myself, and I had no issues like that...?
Like, a Totodile from the female trainer in Crystal had a female OT in Emerald. And that applied to trading both ways...

Trading Pokémon to Gen 1 removes the OT's gender from their data, so that may be a reason for that...?

If not, can you provide a dump of Crystal's save?

**Comment by sbower213** [comment]
ah, ignore that! i completely forgot the pokemon i traded over to emerald was one i originally added into my game via pokehex; i kept the same trainer name but must have forgotten to change the OT gender. other trades with pokemon from the cartridge work fine. :)
