### ISSUE TITLE
Repro cards

### ISSUE THREAD

**Issue by kazzaluis** [Lorenzooone/Pokemon-Gen3-to-Gen-X#13]
I have 2 repro cards with this PCB   both has 1mb flash save memory 
![7424b87f-2592-4013-be0b-68242e9409e4](https://github.com/user-attachments/assets/81a4c2b5-83a2-4979-94dc-c8a5ad0eaba9)

I wrote the clean tool in this and I have a repro game with the same PCB with a fire red room in 

The tool crashed every time in trying to save progress 

Is this happen for what ?

The tool in this repro cart
The game in that repro cart
Is this won't happen with a original cartridge ?

**Comment by kazzaluis** [comment]
![IMG_20240908_073314](https://github.com/user-attachments/assets/780101d3-d8a8-43e0-82d8-f66e6d95ad19)

**Comment by Lorenzooone** [comment]
The issue is using a reproduction cartridge for the actual game (Fire Red).
Games on those are patched to save differently. The tool cannot realistically handle saving to those, as it's a very risky operation.

I actually wonder whether the repro cart works with the Pal Park transfers in Gen 4 or not...

The tool does work with flashcarts though.

Not going to fix this.

**Comment by kazzaluis** [comment]
So tool will work with a original cart ? Even if it's wrote in a repro cart ?

**Comment by Lorenzooone** [comment]
Yes, that is not a problem.

**Comment by kazzaluis** [comment]
Okay the problem are the repro carts will work tool in repro cart and original cart
