### ISSUE TITLE
More trade options?

### ISSUE THREAD

**Issue by ActuallyTheOwner** [Lorenzooone/Pokemon-Gen3-to-Gen-X#14]
I feel gen 3 should have an option to copy pokemon into ram and inject into a gen 3 cart that you swapped the cartage for. 
This would not work for gen 1 & 2 as the GBA soft resets when swapping to a GBC or GB cart.

**Comment by ActuallyTheOwner** [comment]
Oh while I am on this, it would be interesting if after this was implemented, a way to edit Pokemon was introduced even if it were to change species values that are used only in some romhacks such as the unused unown.

**Comment by Lorenzooone** [comment]
For 1), no. This isn't a tool for cloning. It's for trading. And if we assume that is the goal, there is no way to transfer the Pokémon between two cartridges with cart swapping **in a safe manner**. You'd end up with a [Two generals' problem](https://en.wikipedia.org/wiki/Two_Generals'_Problem), while risking the Pokémon data.

For 2), no idea what you mean...? The code is ready for transfers of any Pokémon which exists in Gen 3, but supporting Gen 1/2 romhacks wouldn't make sense for regular users. It could be something interesting done in a branch for games with expanded Pokédex (like Pokémon Brown or Prism, for example), but not for the main release.
If you mean Gen 3 romhacks support, it would be better if the developers reached out and worked on a proper branch of this (like the Gen 1/2 romhacks model), instead of making a tool to edit data that could potentially harm regular games. **Safety of the user and their data is paramount.**
In general, this is mainly for trading and a couple of nice extras to fix possible issues that the users may face based on my experience. It's not to straight up edit Pokémon data. PkHex (PkHax to freely edit the data, in this case) and other tools exist for that.

Regardless of that, the code for this is open source, so if you're interested, you can go on and fork this/make your own tool/project, provided you respect the license this code is distributed with, if you use it.

Closing for now.
