### ISSUE TITLE
How to run inside terminal emulator

### ISSUE THREAD

**Issue by Gronis** [Lorenzooone/Pokemon-Gen3-to-Gen-X#6]
I want to dig into the code and therefore need to understand a good dev workflow. I'm trying to use mGBA to multiboot but it always boots into the pokemon gba rom. Could you describe how you worked on this? Did you always flash a real gba to test out each build? Did you use an emulator?

Thanks for building this great piece of software.

**Comment by Lorenzooone** [comment]
Hi!
The workflow depended on what I wanted to test. For regular features, I'd just run the program in an emulator with a predefined savefile.
I basically had a script that is the equivalent of this:
```
cp "base_save.sav" "Pokemon-Trade-Gen3-to-Gen-12_mb.sav"
mgba "Pokemon-Trade-Gen3-to-Gen-12_mb.gba"

```
Due to how this is coded, it will load the copied savefile just fine.

Multiboot loading of a different save is possible, but still a bit wonky on mgba. In QT builds there is a way to cart swap, but it has a couple of bugs (that I have reported, so they're aware of this).

For more in depth tests that required real GBAs/GBCs, I have a piece of hardware that I can use to Multiboot into the ROM through a USB<->Link Cable connection. So I don't have to flash the ROM each and every time. The "Send Multiboot" option in the software itself also comes in handy to spread this to other GBAs. The basic code for multibooting through USB is available here: https://github.com/Lorenzooone/PokemonGB_Online_Trades, with the m option for usb_trading.py.
In theory, any setup that allows multibooting could work. So even something like a Wii or a Gamecube.

**Comment by Gronis** [comment]
Thanks! This is great information :)

I've been looking into improving the UI look and feel. Mainly making a proper pixel renderer for text so that each character does not have to use an entire tile, but can be variable in size. This is how most GBA games (and the pokemon games) render text. This way text is more readable and more text can fit onto the screen. For example spacing does not need to be exactly 8 pixels between lines when some vertical spacing is needed.

This is what my design looked like when I was going to implement my own version of something like this, before I discovered your project: https://seafile.robingronberg.se/d/7963db900c814f7198b3/

Now, I'm thinking about taking your existing design and apply this font render to it. It should make some of the screens much more readable like the stats screen which is cramped right now.

Would this help be appreciated? Just asking so that I don't throw my time away building something that won't be merged anyways.

**Comment by Lorenzooone** [comment]
A VWF (Variable Width Font) would definitely be appreciated!
src/print_system.c should be where you'd want to start. Though at that point, I'd make a separate file specifically for font stuff.
If any issues come up, let me know and I'll try to help!

**Comment by Gronis** [comment]
I'll start to look at it tomorrow and if I'm stuck at something, I'll reach out.

Right now, I'm working on a simple cli tool to convert the png tile map from png into a binary format that can be loaded from code. The font will have support for up to 4 colors (rather than 2), because it looks so much nicer with some dropped shadows. 

I will also fix a USB-multiboot setup that you mentioned so that I can run on real hardware at some point.

Thanks for the help, and thanks for building this software. It's a huge achievement :)
