### ISSUE TITLE
Avoid trouble with big company

### ISSUE THREAD

**Issue by Gronis** [Lorenzooone/Pokemon-Gen3-to-Gen-X#7]
There are some bundled sprites that might get this project into trouble at some point if it grows in popularity. I think there should be a plan to avoid getting into trouble. I know Pokemon Showdown and PKSM (and possibly others) are using assets but still seems to be outside "Big Enterprise" radar. However GB and GBA roms did not have the same fortune in the past.

I see 4 possible solutions:

1. Do nothing and risk being taken down by "Big Enterprise"
2. Remove sprites (least appealing option)
3. Replace sprites with community versions (if there are such sprites available)
4. Load the sprites of the GBA rom cartridge instead. This is probably the most technical and I'm not even sure if it's possible to read data from the cartridge like that.

Consider closing this if such a risk seems negligible.

**Comment by Lorenzooone** [comment]
When taking down a project, a notice is first submitted, and a developer can comply with the requests of the Company.
Considering PKHeX, pokesprite and Bulbapedia are still up, I see it very unlikely for GameFreak or TPC to come after any project. Especially since this does not make any money. For good measure, I did put a notice about the copyright of the sprites and other resources. It doesn't mean anything, but it shows that there is good will in recognizing copyright.

Loading sprites from the Cartridges is definitely possible (the GameCube Pokémon games and some DS games do this, for example), however it would result in a downgraded experience for people needing to manually place saves (for whatever reason they might have).

I do not see myself ever doing it for Copyright reasons unless a notice about it actually arrives.

There is a benefit to loading from Cart though in terms of space, which is actually interesting. It would save about 128 KBs of the 256 KBs of total available space. Basically half of the current ROM size. It could be something developed as a special build option and/or if the project grows too big.
