### ISSUE TITLE
Entering Clock Settings resets working real time clock

### ISSUE THREAD

**Issue by Gronis** [Lorenzooone/Pokemon-Gen3-to-Gen-X#9]
Simply entering the Clock Settings with an inserted cartridge and than immediately exit again without saving (clicking B button) will reset the real time clock on a working battery. I know there is a warning stating that updating the time will screw up the clock of a working RTC, but simply entering the clock setting seems to reset it as well.

**Comment by Lorenzooone** [comment]
It's an issue with older versions of agbabi.
It's been very recently fixed in https://github.com/felixjones/agbabi/pull/22 .
I was waiting for things to stabilize before updating both the most recent release, and the version of said library that needs to be used to compile this.

Will update it in a couple of days.

**Comment by Gronis** [comment]
Great to hear!
I was thinking that I would be nice to be able to edit RTC clock as well as save clock. Right now, I'm using GBA_RTCRead to edit the RTC, but having this functionality in Pokemon Gen3 to GenX would be really nice! Maybe no UI change should be done, just save to RTC clock as well as eeprom flash when saving clock setting?

Looking at https://github.com/megaboyexe/GBA_RTCRead/blob/master/rtcread/source/rtcread.c, its less than 100 lines of code to read and write RTC.

**Comment by Lorenzooone** [comment]
Having two editable clocks would just lead to unnecessary confusion for the final user, since you can edit just one to achieve the same result. Plus, editing the save data clock makes it work with dry batteries as well, which is the state in which most carts are.
To be clear, the required code is already in agbabi, and you can use the branch https://github.com/Lorenzooone/Pokemon-Gen3-to-Gen-X/blob/time_setter to do that exact thing.
I just don't see any benefit in including it into the main application, though (which would offset the risk of confusing the user).

**Comment by Gronis** [comment]
What you are saying is what I meant. The same setting changes both in-game save and RTC clock. That is what you want anyways. I agree that having two clocks to edit is confusing.

What I meant is that it would be nice if the RTC is also updated together with in-game clock setting when saving the clock settings. That way, a second application is not needed to also update the RTC afterwards using another application in order to make sure they are in sync again.

**Comment by Lorenzooone** [comment]
I think there is some confusion here in how this all works...
They are summed together to create the actual clock. They are always in sync.
You do not need to use anything else.

**Comment by Lorenzooone** [comment]
Newest release fixes this. Closing the issue.

**Comment by Gronis** [comment]
Hi Lorenzooone, I've used rebased on you latest commit and I still have this issue. When simply entering the clock settings, then exit, and then check the realtime clock in "Real Time Clock Reader DS" application, it has reset the RTC to 01/01/2000 which disables all time events until the RTC has caught up with the save file time clock.

Steps to reproduce:

1. Insert gba game with working RTC battery in slot 2 and nds flash cart in slot 1 with "rtcread-ds.nds" application available.
2. In "rtcread-ds.nds", set the time to something a bit after 01/01/2000 (example 02/02/2002)
3. Load gba game into "Pokemon Gen3 to Gen-X" and enter clock settings.
4. Exit clock settings with B (without saving)
5. Do step 1 again
6. Observe that the RTC time has now reset back to 01/01/2000

If you do all the steps except skip entering the clock settings, the RTC time will be retained. (e.g still 02/02/2002) when loading up the RTC time in step 6.

**Comment by Lorenzooone** [comment]
I don't know what your build setup is, but you MUST update the agbabi version you're using.
If you're using the docker images I provide, it's going to be as simple as re-downloading the images.
If you're using your own images, you will have to build them again using the Dockerfile.

**Comment by Gronis** [comment]
Ah yea, forgot to update agbabi. My bad

**Comment by Gronis** [comment]
Updating agbabi to v2.1.6 seems to do the trick. Thanks for fixing!
